http:
  port: "8081"

scheduler:
  cpuIntensive:
    size: "8"

clouderby:
  host: "mule-clouderby-2m6ahj.pnwfdv.jpn-e1.cloudhub.io"
  port: "443"
  user: "mule"
  password: "mule123"

sf:
  host: "trailsignup-1c3ba81ec14b1c.my.salesforce.com"
  tokenUrl: "https://trailsignup-1c3ba81ec14b1c.my.salesforce.com/services/oauth2/token"
  clientId: "${sf.clientId}"
  clientSecret: "${sf.clientSecret}"

oracle:
  host: "192.168.11.6"
  port: "11521"
  user: "mule"
  password: "Mule_l23_Soft_Oracle"
  serviceId: "FREEPDB1"
