http:
  port: "8891"

scheduler:
  cpuIntensive:
    size: "2"

clouderby:
  host: "localhost"
  port: "8081"
  user: "mule"
  password: "${secure.clouderby.password}"

sf:
  host: "trailsignup-1c3ba81ec14b1c.my.salesforce.com"
  tokenUrl: "https://trailsignup-1c3ba81ec14b1c.my.salesforce.com/services/oauth2/token"
  clientId: "${sf.clientId}"
  clientSecret: "${sf.clientSecret}"

oracle:
  host: "192.168.11.6"
  port: "11521"
  user: "mule"
  password: "${secure.oracle.password}"
  serviceId: "FREEPDB1"

