http:
  port: "8891"

scheduler:
  cpuIntensive:
    size: "2"

clouderby:
  host: "localhost"
  port: "8081"
  user: "mule"
  password: "${CLOUDERBY_PASSWORD}"

sf:
  host: "trailsignup-1c3ba81ec14b1c.my.salesforce.com"
  clientId: "${SF_CLIENT_ID}"
  clientSecret: "${SF_CLIENT_SECRET}"

oracle:
  host: "cloud-services.demos.mulesoft.com"
  port: "32627"
  user: "mule"
  password: "${ORACLE_PASSWORD}"
  serviceId: "muledb"

