http:
  port: "8081"

scheduler:
  cpuIntensive:
    size: "8"

clouderby:
  host: "hqlite-mule-server-2m6ahj.pnwfdv.jpn-e1.cloudhub.io"
  port: "443"
  user: "mule"
  password: "${CLOUDERBY_PASSWORD}"

sf:
  host: "trailsignup-1c3ba81ec14b1c.my.salesforce.com"
  clientId: "${SF_CLIENT_ID}"
  clientSecret: "${SF_CLIENT_SECRET}"

oracle:
  host: "cloud-services.demos.mulesoft.com"
  port: "32627"
  user: "mule"
  password: "${ORACLE_PASSWORD}"
  serviceId: "muledb"
